const data = [
    {
        row : "A",
        index : 0,
        seats : [
            { pos : 1, status : "empty", isSelected : false, type : "premium", price : 480},
            { pos : 2, status : "empty", isSelected : false, type : "premium", price : 480},
            { pos : 3, status : "empty", isSelected : false, type : "premium", price : 480},
            { pos : 4, status : "available", isSelected : false, type : "premium", price : 480},
            { pos : 5, status : "available", isSelected : false, type : "premium", price : 480},
            { pos : 6, status : "empty", isSelected : false, type : "premium", price : 480},
            { pos : 7, status : "unavailable", isSelected : false, type : "premium", price : 480},
            { pos : 8, status : "unavailable", isSelected : false, type : "premium", price : 480},
            { pos : 9, status : "empty", isSelected : false, type : "premium", price : 480},
            { pos : 10, status : "unavailable", isSelected : false, type : "premium", price : 480},
            { pos : 11, status : "unavailable", isSelected : false, type : "premium", price : 480},
            { pos : 12, status : "empty", isSelected : false, type : "premium", price : 480},
            { pos : 13, status : "available", isSelected : false, type : "premium", price : 480},
            { pos : 14, status : "available", isSelected : false, type : "premium", price : 480},
            { pos : 15, status : "empty", isSelected : false, type : "premium", price : 480},
            { pos : 16, status : "available", isSelected : false, type : "premium", price : 480},
            { pos : 17, status : "available", isSelected : false, type : "premium", price : 480},
            { pos : 18, status : "empty", isSelected : false, type : "premium", price : 480},
            { pos : 19, status : "available", isSelected : false, type : "premium", price : 480},
            { pos : 20, status : "available", isSelected : false, type : "premium", price : 480},
            { pos : 21, status : "empty", isSelected : false, type : "premium", price : 480},
            { pos : 22, status : "available", isSelected : false, type : "premium", price : 480},
            { pos : 23, status : "available", isSelected : false, type : "premium", price : 480},
            { pos : 24, status : "empty", isSelected : false, type : "premium", price : 480},
            { pos : 25, status : "empty", isSelected : false, type : "premium", price : 480}
        ]
    },
    {
        row : "B",
        index : 1,
        seats : [
            { pos : 1, status : "empty", isSelected : false, type : "premium", price : 480},
            { pos : 2, status : "empty", isSelected : false, type : "premium", price : 480},
            { pos : 3, status : "empty", isSelected : false, type : "premium", price : 480},
            { pos : 4, status : "unavailable", isSelected : false, type : "premium", price : 480},
            { pos : 5, status : "unavailable", isSelected : false, type : "premium", price : 480},
            { pos : 6, status : "empty", isSelected : false, type : "premium", price : 480},
            { pos : 7, status : "available", isSelected : false, type : "premium", price : 480},
            { pos : 8, status : "available", isSelected : false, type : "premium", price : 480},
            { pos : 9, status : "empty", isSelected : false, type : "premium", price : 480},
            { pos : 10, status : "available", isSelected : false, type : "premium", price : 480},
            { pos : 11, status : "available", isSelected : false, type : "premium", price : 480},
            { pos : 12, status : "empty", isSelected : false, type : "premium", price : 480},
            { pos : 13, status : "available", isSelected : false, type : "premium", price : 480},
            { pos : 14, status : "available", isSelected : false, type : "premium", price : 480},
            { pos : 15, status : "empty", isSelected : false, type : "premium", price : 480},
            { pos : 16, status : "unavailable", isSelected : false, type : "premium", price : 480},
            { pos : 17, status : "unavailable", isSelected : false, type : "premium", price : 480},
            { pos : 18, status : "empty", isSelected : false, type : "premium", price : 480},
            { pos : 19, status : "empty", isSelected : false, type : "premium", price : 480},
            { pos : 20, status : "available", isSelected : false, type : "premium", price : 480},
            { pos : 21, status : "available", isSelected : false, type : "premium", price : 480},
            { pos : 22, status : "empty", isSelected : false, type : "premium", price : 480},
            { pos : 23, status : "available", isSelected : false, type : "premium", price : 480},
            { pos : 24, status : "available", isSelected : false, type : "premium", price : 480},
            { pos : 25, status : "empty", isSelected : false, type : "premium", price : 480}
        ]
    },
    {
        row : "C",
        index : 2,
        seats : [
            { pos : 1, status : "empty", isSelected : false, type : "standard", price : 280},
            { pos : 2, status : "empty", isSelected : false, type : "standard", price : 280},
            { pos : 3, status : "empty", isSelected : false, type : "standard", price : 280},
            { pos : 4, status : "empty", isSelected : false, type : "standard", price : 280},
            { pos : 5, status : "unavailable", isSelected : false, type : "standard", price : 280},
            { pos : 6, status : "unavailable", isSelected : false, type : "standard", price : 280},
            { pos : 7, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 8, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 9, status : "unavailable", isSelected : false, type : "standard", price : 280},
            { pos : 10, status : "unavailable", isSelected : false, type : "standard", price : 280},
            { pos : 11, status : "unavailable", isSelected : false, type : "standard", price : 280},
            { pos : 12, status : "unavailable", isSelected : false, type : "standard", price : 280},
            { pos : 13, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 14, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 15, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 16, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 17, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 18, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 19, status : "empty", isSelected : false, type : "standard", price : 280},
            { pos : 20, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 21, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 22, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 23, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 24, status : "unavailable", isSelected : false, type : "standard", price : 280},
            { pos : 25, status : "unavailable", isSelected : false, type : "standard", price : 280}
        ]
    },
    {
        row : "D",
        index : 3,
        seats : [
            { pos : 1, status : "empty", isSelected : false, type : "standard", price : 280},
            { pos : 2, status : "empty", isSelected : false, type : "standard", price : 280},
            { pos : 3, status : "empty", isSelected : false, type : "standard", price : 280},
            { pos : 4, status : "empty", isSelected : false, type : "standard", price : 280},
            { pos : 5, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 6, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 7, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 8, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 9, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 10, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 11, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 12, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 13, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 14, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 15, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 16, status : "unavailable", isSelected : false, type : "standard", price : 280},
            { pos : 17, status : "unavailable", isSelected : false, type : "standard", price : 280},
            { pos : 18, status : "unavailable", isSelected : false, type : "standard", price : 280},
            { pos : 19, status : "empty", isSelected : false, type : "standard", price : 280},
            { pos : 20, status : "unavailable", isSelected : false, type : "standard", price : 280},
            { pos : 21, status : "unavailable", isSelected : false, type : "standard", price : 280},
            { pos : 22, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 23, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 24, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 25, status : "available", isSelected : false, type : "standard", price : 280}
        ]
    },
    {
        row : "E",
        index : 4,
        seats : [
            { pos : 1, status : "empty", isSelected : false, type : "standard", price : 280},
            { pos : 2, status : "empty", isSelected : false, type : "standard", price : 280},
            { pos : 3, status : "empty", isSelected : false, type : "standard", price : 280},
            { pos : 4, status : "empty", isSelected : false, type : "standard", price : 280},
            { pos : 5, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 6, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 7, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 8, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 9, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 10, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 11, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 12, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 13, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 14, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 15, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 16, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 17, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 18, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 19, status : "empty", isSelected : false, type : "standard", price : 280},
            { pos : 20, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 21, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 22, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 23, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 24, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 25, status : "available", isSelected : false, type : "standard", price : 280}
        ]
    },
    {
        row : "F",
        index : 5,
        seats : [
            { pos : 1, status : "empty", isSelected : false, type : "standard", price : 280},
            { pos : 2, status : "empty", isSelected : false, type : "standard", price : 280},
            { pos : 3, status : "empty", isSelected : false, type : "standard", price : 280},
            { pos : 4, status : "empty", isSelected : false, type : "standard", price : 280},
            { pos : 5, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 6, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 7, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 8, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 9, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 10, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 11, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 12, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 13, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 14, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 15, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 16, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 17, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 18, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 19, status : "empty", isSelected : false, type : "standard", price : 280},
            { pos : 20, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 21, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 22, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 23, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 24, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 25, status : "available", isSelected : false, type : "standard", price : 280}
        ]
    },
    {
        row : "G",
        index : 6,
        seats : [
            { pos : 1, status : "empty", isSelected : false, type : "standard", price : 280},
            { pos : 2, status : "empty", isSelected : false, type : "standard", price : 280},
            { pos : 3, status : "empty", isSelected : false, type : "standard", price : 280},
            { pos : 4, status : "empty", isSelected : false, type : "standard", price : 280},
            { pos : 5, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 6, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 7, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 8, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 9, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 10, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 11, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 12, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 13, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 14, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 15, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 16, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 17, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 18, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 19, status : "empty", isSelected : false, type : "standard", price : 280},
            { pos : 20, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 21, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 22, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 23, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 24, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 25, status : "available", isSelected : false, type : "standard", price : 280}
        ]
    },
    {
        row : "H",
        index : 7,
        seats : [
            { pos : 1, status : "unavailable", isSelected : false, type : "standard", price : 280},
            { pos : 2, status : "unavailable", isSelected : false, type : "standard", price : 280},
            { pos : 3, status : "unavailable", isSelected : false, type : "standard", price : 280},
            { pos : 4, status : "empty", isSelected : false, type : "standard", price : 280},
            { pos : 5, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 6, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 7, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 8, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 9, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 10, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 11, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 12, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 13, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 14, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 15, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 16, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 17, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 18, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 19, status : "empty", isSelected : false, type : "standard", price : 280},
            { pos : 20, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 21, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 22, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 23, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 24, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 25, status : "available", isSelected : false, type : "standard", price : 280}
        ]
    },
    {
        row : "I",
        index : 8,
        seats : [
            { pos : 1, status : "unavailable", isSelected : false, type : "standard", price : 280},
            { pos : 2, status : "unavailable", isSelected : false, type : "standard", price : 280},
            { pos : 3, status : "unavailable", isSelected : false, type : "standard", price : 280},
            { pos : 4, status : "empty", isSelected : false, type : "standard", price : 280},
            { pos : 5, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 6, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 7, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 8, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 9, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 10, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 11, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 12, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 13, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 14, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 15, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 16, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 17, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 18, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 19, status : "empty", isSelected : false, type : "standard", price : 280},
            { pos : 20, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 21, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 22, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 23, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 24, status : "available", isSelected : false, type : "standard", price : 280},
            { pos : 25, status : "available", isSelected : false, type : "standard", price : 280}
        ]
    }
];

export default data;

